name: CI
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  coverage:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - uses: artiomtr/jest-coverage-report-action@v2
        with:
          test-script: npm run test
